### PR TITLE
Add proper LICENSE file

### PR DESCRIPTION
**Pull request by ShadowJonathan**
This requires signoff from every single contributor so far

### CODE REVIEW

**Review by buresdv — DISMISSED** [review]
Looks good

**Comment by ShadowJonathan** [comment]
@EricBAndrews, @noloman, @lil5 and @samalone, I can't add you to reviewers, but could you please approve this PR?

Approving this PR means you agree to the re-license, but since this is only adding the LICENSE text proper, that shouldn't be much of an issue.

**Review by sebj — APPROVED** [review]

**Comment by noloman** [comment]
I can't approve but it looks good to me too

**Comment by EricBAndrews** [comment]
I approve

**Comment by samalone** [comment]
I approve

**Comment by buresdv** [comment]
We can take @samalone out of the list, he helped me with getting replies working, but I don’t think he has the time to work on Mlem further

**Review by mormaer — DISMISSED** [review]

**Review by WestonHanners — APPROVED** [review]

**Comment by lil5** [comment]
Are you sure you want to make an iOS app GPL?
Last time I checked even Nextcloud iOS has a special clause to allow itself on the Apple Store.

**Review by lil5 — APPROVED** [review]

**Comment by ShadowJonathan** [comment]
That may actually be a bit of a concern...

**Comment by noloman** [comment]
What exactly?

**Comment by buresdv** [comment]
If anyone has ideas about which other license to use, please share your ideas.

The main requirements are:
- The app's source is available to the public, and anyone can change it in order to improve the app. They can also contribute their code and compile the app themselves.
- Nobody but us can make money from the app or any derivates of it (covered by Commons Clause).
- We CAN make money from the app.
- The app can be published to the App Store.
- Any modified versions have to keep the original license. In other words, someone can’t just come along, remove the part about them being banned from making money from it, and then make money from it.

I bet there are some important points that I forgot (I'm still very sick and can’t think well), so I trust that

**Comment by lil5** [comment]
If you copy the following into this repository I guess you'll be covered 

```
The Mlem iOS developers are aware that the terms of service that
apply to apps distributed via Apple's App Store services may conflict
with rights granted under the Mlem iOS license, the "GNU GPLv3 amended by the Commons Clause v1". We have committed not to pursue any license
violation that results solely from the conflict between the "GNU GPLv3 amended by the Commons Clause v1"
or any later version and the Apple App Store terms of service.
```

**Comment by ShadowJonathan** [comment]
@lil5 do you think it's ok if i just copy that to the license file?

**Comment by lil5** [comment]
_Im not a lawyer and have zero training in law_

Sure

**Comment by ShadowJonathan** [comment]
Added a clause that makes this publishable to the Apple App Store, IANAL, but I think everyone would have to approve of this change, so i'll mention those who approve via comment, and i'll request review to those who do it via review approval;

- [ ] @EricBAndrews
- [ ] @noloman
- [ ] @samalone

**Review by lil5 — APPROVED** [review]

**Comment by noloman** [comment]
approved

**Review by sebj — DISMISSED** [review]

**Review by buresdv — DISMISSED** [review]

**Comment by EricBAndrews** [comment]
Approved

**Review by mormaer — APPROVED** [review]

**Comment by JakeShirley** [comment]
LGTM

**Comment by BrooklynMan** [comment]
I think this should wait until we have our conference call

**Review by WestonHanners — CHANGES_REQUESTED** [review]
Holding for comments from @BrooklynMan

**Review by WestonHanners — DISMISSED** [review]

**Comment by ShadowJonathan** [comment]
Regarding [2c05805](https://github.com/mormaer/Mlem/pull/171/commits/2c05805770695cad6e6e13b6810cd240ac740576);
- Added full text of the GPL 3 license
- Changed the licensor name from David to The Mlem Group
- Added some seperators between the clauses

**Review by EricBAndrews — APPROVED** [review]

**Comment by BrooklynMan** [comment]
added in PR #228

**Review by BrooklynMan — APPROVED** [review]
this is the basic license text required

**Comment by lil5** [comment]
In the read me it states that the project is open-source, that is just not true. 

The correct term is **source available**

The commons clause inhibits 1 and 3 of the open source definition (OSI)

https://en.wikipedia.org/wiki/The_Open_Source_Definition

**Pull request merged**
