### PR TITLE
Run SwiftLint on changed code when a PR is created

### PR DESCRIPTION
**Pull request by MrAusnadian**
# Checklist
- [x] I have described what this PR contains

**Choose one of the following two options:**
- - [x] This PR does not introduce major changes
- - [ ] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*

**Choose one of the following two options:**
- - [x] This PR does not change the UI in any way
- - [ ] This PR adds new UI elements / changes the UI, and I have attached pictures or videos of the new / changed UI elements

# Pull Request Information

## About this Pull Request
Run SwiftLint on changed code when a PR is created using GitHub Actions workflow file

## Screenshots and Videos
If any code fails linting, the warnings and errors will be published to an HTML report that is attached to the Action run as an Artifact:
image

### CODE REVIEW

**Review by mormaer — CHANGES_REQUESTED** [review]
Hi - thanks for this, this is something I've been meaning to get into the project along with `swiftformat`

Personally I'd prefer it to be done as a [build phase locally](https://github.com/realm/SwiftLint#xcode), there are some downsides to it in that it's harder to keep everyone in sync version wise, but it won't use any GH actions time and also gives feedback while developing, which saves discovering the issue after you've pushed

**Comment by MrAusnadian** [comment]
@mormaer Yeah, that's fair. I'm not running on a Mac, so I can't help with that, unfortunately. Feel free to close this PR if you want

**Comment by JakeShirley** [comment]
I _think_ this addressed with #304 , but because we don't have CI builds set up it might still be nice to run this as a first step.

**Comment by JakeShirley** [comment]
Closing, implemented in #351

**Pull request closed without merging**
