### PR TITLE
App shortcuts

### PR DESCRIPTION
**Pull request by tht7**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - #416
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
Added Home Screen app shortcuts

## Screenshots and Videos
IMG_1876DC524095-1

## Additional Context
**Any additional context you'd like to add to help us review this PR**

### CODE REVIEW

**Comment by JakeShirley** [comment]
Not that I love the icons we have now, but can you match the ones we have in the community list view?

**Review by WestonHanners — DISMISSED** [review]
🔥

**Comment by tht7** [comment]
> Not that I love the icons we have now, but can you match the ones we have in the community list view?
hmmm A or B?
A:
IMG_7233

B:
IMG_7234

?

**Comment by ShadowJonathan** [comment]
Closed in favour of https://github.com/mlemgroup/mlem/pull/11

**Pull request closed without merging**
