### PR TITLE
Commons Clause is not Open Source but Source Available 

### PR DESCRIPTION
**Pull request by lil5**
# Checklist
- [x] I have described what this PR contains

**Choose one of the following two options:**
- [x] This PR does not introduce major changes
- [ ] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*

**Choose one of the following two options:**
- [x] This PR does not change the UI in any way
- [ ] This PR adds new UI elements / changes the UI, and I have attached pictures or videos of the new / changed UI elements

# Pull Request Information

## About this Pull Request
Remove the word open-source from the readme as the Commons Clause denies the 1st and 3rd rule in the Open Source Definition (which is published by the OSI)

## Additional Context

The Open Source Definition: https://opensource.org/osd/
FSF: https://www.gnu.org/licenses/license-list.html#comclause
Wikipedia definition: https://en.wikipedia.org/wiki/Source-available_software#Commons_Clause

- [ ] 1. Also the `LICENSE` file is using the GPLv3.0 text first!
This ensures that Github considers this project to be licensed under the GPLv3.0, please move the Commons Clause text to the beginning so that Github reads that first. 
- [ ] 2. There is a `gpl-3.0.txt` I advise this to be removed as this just create confusion under what license this software is under and the text for the GPL license is already in the LICENSE file.

### CODE REVIEW

**Comment by BrooklynMan** [comment]
GPL 3.0 + Common Clause is open source. This issue has been discussed ad nauseam, and this is our final position on the matter.

**Comment by lil5** [comment]
@BrooklynMan Wow, no, fuck you

Below is an insert found on the commons clause official website:

https://commonsclause.com/

Is this “Open Source”?

No.

“Open source”, has a specific definition that was written years ago and is stewarded by the Open Source Initiative, which approves Open Source licenses. Applying the Commons Clause to an open source project will mean the source code is available, and meets many of the elements of the Open Source Definition, such as free access to source code, freedom to modify, and freedom to re-distribute, but not all of them. So to avoid confusion, it is best not to call Commons Clause software “open source.”

**Comment by lil5** [comment]
@ShadowJonathan please take another look at this.

**Comment by BrooklynMan** [comment]
you have been reported of trolling, harassment, and uncivil behavior. this matter is settled and closed.

**Pull request closed without merging**
