### PR TITLE
Swiftlint

### PR DESCRIPTION
**Pull request by mormaer**
# Checklist
- [x] I have described what this PR contains

**Choose one of the following two options:**
- - [ ] This PR does not introduce major changes
- - [x] This PR introduces major changes, and I have consulted the *Mlem Development Matrix room*

**Choose one of the following two options:**
- - [x] This PR does not change the UI in any way
- - [ ] This PR adds new UI elements / changes the UI, and I have attached pictures or videos of the new / changed UI elements

# Pull Request Information

## About this Pull Request
This pull request introduces [SwiftLint](https://github.com/realm/SwiftLint#swiftlint) into the project as a build phase.

In addition to this it addresses the current listing errors that are present in the codebase. This partially addresses #157 by covering the linting side, `swiftformat` will be addressed in a separate PR.

The projects README has been updated to highlight use of SwiftLint going forward.

## Additional Context
Although a large PR (we had _alot_ of linting issues) there is no functional changes introduced in this PR.

Instead of seeking a review of every change, I would encourage any reviewer to pull the branch, build and use the app to perform a regression check on behaviour.

### CODE REVIEW

**Comment by WestonHanners** [comment]
can you please also add notes to README.md about the new SwiftLint requirement?

**Comment by JakeShirley** [comment]
How is this ran?  A pipeline?  A build step locally?

**Comment by JakeShirley** [comment]
Better yet, how do I trigger this to force-format my code :D

**Comment by mormaer** [comment]
> How is this ran?  A pipeline?  A build step locally?

It's a build step in XCode, so it will run on each build and produce warnings/errors where necessary.

There's steps in the updated README for installing swiftlint, it's just one command if you already have homebrew

**Comment by mormaer** [comment]
> Better yet, how do I trigger this to force-format my code :D 

You can run it from the terminal with the `--fix` argument but if you're building as you go you get feedback in-line which is normally enough 🙏

**Review by WestonHanners — DISMISSED** [review]

**Review by JakeShirley — APPROVED** [review]

**Pull request merged**
